# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SPI_analyze_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 287)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_DB = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_DB.setGeometry(QtCore.QRect(30, 20, 491, 91))
        self.groupBox_DB.setTitle("")
        self.groupBox_DB.setObjectName("groupBox_DB")
        self.lineEdit_DB = QtWidgets.QLineEdit(self.groupBox_DB)
        self.lineEdit_DB.setGeometry(QtCore.QRect(10, 20, 431, 20))
        self.lineEdit_DB.setObjectName("lineEdit_DB")
        self.toolButton_DB = QtWidgets.QToolButton(self.groupBox_DB)
        self.toolButton_DB.setGeometry(QtCore.QRect(450, 20, 25, 19))
        self.toolButton_DB.setObjectName("toolButton_DB")
        self.label_3 = QtWidgets.QLabel(self.groupBox_DB)
        self.label_3.setGeometry(QtCore.QRect(150, 50, 121, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.groupBox_CSV = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_CSV.setGeometry(QtCore.QRect(30, 120, 491, 91))
        self.groupBox_CSV.setTitle("")
        self.groupBox_CSV.setObjectName("groupBox_CSV")
        self.lineEdit_CSV = QtWidgets.QLineEdit(self.groupBox_CSV)
        self.lineEdit_CSV.setGeometry(QtCore.QRect(10, 20, 431, 20))
        self.lineEdit_CSV.setObjectName("lineEdit_CSV")
        self.toolButton_CSV = QtWidgets.QToolButton(self.groupBox_CSV)
        self.toolButton_CSV.setGeometry(QtCore.QRect(450, 20, 25, 19))
        self.toolButton_CSV.setObjectName("toolButton_CSV")
        self.label_4 = QtWidgets.QLabel(self.groupBox_CSV)
        self.label_4.setGeometry(QtCore.QRect(150, 50, 121, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 214, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_4.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(560, 30, 75, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SPI analyze"))
        self.toolButton_DB.setText(_translate("MainWindow", "..."))
        self.label_3.setText(_translate("MainWindow", "拖入选择文件"))
        self.toolButton_CSV.setText(_translate("MainWindow", "..."))
        self.label_4.setText(_translate("MainWindow", "拖入选择文件"))
        self.pushButton.setText(_translate("MainWindow", "RUN"))
